import { query } from '../../../database/db.js';

export class ScheduleCRepository {
  async upsert(organizationId: string, taxYear: number, payload: Record<string, unknown>) {
    await query(
      `INSERT INTO schedule_c_data (organization_id, tax_year, line_1_gross_receipts_cents, line_2_returns_allowances_cents,
        line_3_subtotal_cents, line_4_cogs_cents, line_5_gross_profit_cents, line_6_other_income_cents,
        line_7_gross_income_cents, line_8_advertising_cents, line_9_car_truck_cents, line_10_commissions_cents,
        line_11_contract_labor_cents, line_12_depletion_cents, line_13_depreciation_cents, line_14_employee_benefit_cents,
        line_15_insurance_cents, line_16a_mortgage_interest_cents, line_16b_other_interest_cents,
        line_17_legal_professional_cents, line_18_office_expense_cents, line_19_pension_plans_cents,
        line_20a_rent_vehicles_cents, line_20b_rent_other_cents, line_21_repairs_cents, line_22_supplies_cents,
        line_23_taxes_licenses_cents, line_24a_travel_cents, line_24b_meals_cents, line_25_utilities_cents,
        line_26_wages_cents, line_27a_other_expenses_cents, line_27_other_expenses_detail,
        line_28_total_expenses_cents, line_29_tentative_profit_cents, line_30_home_office_cents,
        line_31_net_profit_loss_cents, is_draft, computed_at
      ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12, $13, $14, $15, $16,
        $17, $18, $19, $20, $21, $22, $23, $24,
        $25, $26, $27, $28, $29, $30, $31, $32,
        $33, $34, $35, $36, $37, $38, $39, $40
      )
      ON CONFLICT (organization_id, tax_year)
      DO UPDATE SET
        line_1_gross_receipts_cents = EXCLUDED.line_1_gross_receipts_cents,
        line_2_returns_allowances_cents = EXCLUDED.line_2_returns_allowances_cents,
        line_3_subtotal_cents = EXCLUDED.line_3_subtotal_cents,
        line_4_cogs_cents = EXCLUDED.line_4_cogs_cents,
        line_5_gross_profit_cents = EXCLUDED.line_5_gross_profit_cents,
        line_6_other_income_cents = EXCLUDED.line_6_other_income_cents,
        line_7_gross_income_cents = EXCLUDED.line_7_gross_income_cents,
        line_8_advertising_cents = EXCLUDED.line_8_advertising_cents,
        line_9_car_truck_cents = EXCLUDED.line_9_car_truck_cents,
        line_10_commissions_cents = EXCLUDED.line_10_commissions_cents,
        line_11_contract_labor_cents = EXCLUDED.line_11_contract_labor_cents,
        line_12_depletion_cents = EXCLUDED.line_12_depletion_cents,
        line_13_depreciation_cents = EXCLUDED.line_13_depreciation_cents,
        line_14_employee_benefit_cents = EXCLUDED.line_14_employee_benefit_cents,
        line_15_insurance_cents = EXCLUDED.line_15_insurance_cents,
        line_16a_mortgage_interest_cents = EXCLUDED.line_16a_mortgage_interest_cents,
        line_16b_other_interest_cents = EXCLUDED.line_16b_other_interest_cents,
        line_17_legal_professional_cents = EXCLUDED.line_17_legal_professional_cents,
        line_18_office_expense_cents = EXCLUDED.line_18_office_expense_cents,
        line_19_pension_plans_cents = EXCLUDED.line_19_pension_plans_cents,
        line_20a_rent_vehicles_cents = EXCLUDED.line_20a_rent_vehicles_cents,
        line_20b_rent_other_cents = EXCLUDED.line_20b_rent_other_cents,
        line_21_repairs_cents = EXCLUDED.line_21_repairs_cents,
        line_22_supplies_cents = EXCLUDED.line_22_supplies_cents,
        line_23_taxes_licenses_cents = EXCLUDED.line_23_taxes_licenses_cents,
        line_24a_travel_cents = EXCLUDED.line_24a_travel_cents,
        line_24b_meals_cents = EXCLUDED.line_24b_meals_cents,
        line_25_utilities_cents = EXCLUDED.line_25_utilities_cents,
        line_26_wages_cents = EXCLUDED.line_26_wages_cents,
        line_27a_other_expenses_cents = EXCLUDED.line_27a_other_expenses_cents,
        line_27_other_expenses_detail = EXCLUDED.line_27_other_expenses_detail,
        line_28_total_expenses_cents = EXCLUDED.line_28_total_expenses_cents,
        line_29_tentative_profit_cents = EXCLUDED.line_29_tentative_profit_cents,
        line_30_home_office_cents = EXCLUDED.line_30_home_office_cents,
        line_31_net_profit_loss_cents = EXCLUDED.line_31_net_profit_loss_cents,
        is_draft = EXCLUDED.is_draft,
        computed_at = NOW(),
        updated_at = NOW()`,
      [
        organizationId,
        taxYear,
        payload.line_1_gross_receipts_cents,
        payload.line_2_returns_allowances_cents,
        payload.line_3_subtotal_cents,
        payload.line_4_cogs_cents,
        payload.line_5_gross_profit_cents,
        payload.line_6_other_income_cents,
        payload.line_7_gross_income_cents,
        payload.line_8_advertising_cents,
        payload.line_9_car_truck_cents,
        payload.line_10_commissions_cents,
        payload.line_11_contract_labor_cents,
        payload.line_12_depletion_cents,
        payload.line_13_depreciation_cents,
        payload.line_14_employee_benefit_cents,
        payload.line_15_insurance_cents,
        payload.line_16a_mortgage_interest_cents,
        payload.line_16b_other_interest_cents,
        payload.line_17_legal_professional_cents,
        payload.line_18_office_expense_cents,
        payload.line_19_pension_plans_cents,
        payload.line_20a_rent_vehicles_cents,
        payload.line_20b_rent_other_cents,
        payload.line_21_repairs_cents,
        payload.line_22_supplies_cents,
        payload.line_23_taxes_licenses_cents,
        payload.line_24a_travel_cents,
        payload.line_24b_meals_cents,
        payload.line_25_utilities_cents,
        payload.line_26_wages_cents,
        payload.line_27a_other_expenses_cents,
        payload.line_27_other_expenses_detail,
        payload.line_28_total_expenses_cents,
        payload.line_29_tentative_profit_cents,
        payload.line_30_home_office_cents,
        payload.line_31_net_profit_loss_cents,
        payload.is_draft,
        payload.computed_at
      ]
    );
  }
}
